apiVersion: v1
kind: ConfigMap
metadata:
  name: nlp-toolkit-config
  labels:
    app: nlp-toolkit
data:
  # Add any configuration values here
  # For example:
  # LOG_LEVEL: "INFO"
  # MAX_WORKERS: "2"
