apiVersion: apps/v1
kind: Deployment
metadata:
  name: nlp-toolkit
  labels:
    app: nlp-toolkit
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nlp-toolkit
  template:
    metadata:
      labels:
        app: nlp-toolkit
    spec:
      containers:
      - name: nlp-toolkit
        image: registry.hamravesh.com/your-username/nlp-toolkit:latest
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: HF_HOME
          value: "/opt/.cache/huggingface"
        - name: TRANSFORMERS_CACHE
          value: "/opt/.cache/huggingface"
        - name: NLTK_DATA
          value: "/opt/.cache/nltk"
        - name: STANZA_RESOURCES_DIR
          value: "/opt/.cache/stanza"
        - name: TOKENIZERS_PARALLELISM
          value: "false"
        - name: MPLCONFIGDIR
          value: "/opt/.cache/matplotlib"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: cache-volume
          mountPath: /opt/.cache
      volumes:
      - name: cache-volume
        emptyDir: {}
      restartPolicy: Always
